### ISSUE TITLE
issue when using TLS auth on external etcd

### ISSUE THREAD

**Issue by streamnsight** [oracle/oci-service-broker#39]
```
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at com.oracle.oci.osb.store.EtcdStore.<init>(EtcdStore.java:93)
	at com.oracle.oci.osb.store.DataStoreFactory.createDataStore(DataStoreFactory.java:38)
	at com.oracle.oci.osb.store.DataStoreFactory.<clinit>(DataStoreFactory.java:13)
	... 53 more
Caused by: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:195)
	at com.oracle.oci.osb.store.EtcdStore.<init>(EtcdStore.java:78)
```

My cert is valid, I can use it manually directly with `etcdctl` but it fails in the java code.

An idea what could be wrong?

Full trace:
```
+ TAGS=
+ init --port 9998 --privatekey /var/run/oci-service-broker/privatekey --tlsEnabled false --log.configfile /oci-service-broker/config/jul-config.properties --logLevel INFO --ociSdkLogLevel INFO --jvmProps '' --storeType etcd --apiServerCaCerts /var/run/secrets/kubernetes.io/serviceaccount/ca.crt --etcd.servers https://etcd-0.etcd-headless.oci-service-broker.svc.cluster.local:2379,https://etcd-1.etcd-headless.oci-service-broker.svc.cluster.local:2379,https://etcd-2.etcd-headless.oci-service-broker.svc.cluster.local:2379 --etcd.client.tls.enabled true
+ ((  22 > 0  ))
+ case "${1}" in
+ PORT=9998
+ shift
+ shift
+ ((  20 > 0  ))
+ case "${1}" in
+ PRIVATEKEY=/var/run/oci-service-broker/privatekey
+ shift
+ shift
+ ((  18 > 0  ))
+ case "${1}" in
+ TLS_ENABLED=false
+ shift
+ shift
+ ((  16 > 0  ))
+ case "${1}" in
+ LOG_CONFIG_FILE=/oci-service-broker/config/jul-config.properties
+ shift
+ shift
+ ((  14 > 0  ))
+ case "${1}" in
+ LOG_LEVEL=INFO
+ shift
+ shift
+ ((  12 > 0  ))
+ case "${1}" in
+ OCI_SDK_LOG_LEVEL=INFO
+ shift
+ shift
+ ((  10 > 0  ))
+ case "${1}" in
+ JVM_PROPS=
+ shift
+ shift
+ ((  8 > 0  ))
+ case "${1}" in
+ STORE_TYPE=etcd
+ shift
+ shift
+ ((  6 > 0  ))
+ case "${1}" in
+ API_SERVER_CA_CERTS=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
+ shift
+ shift
+ ((  4 > 0  ))
+ case "${1}" in
+ ETCD_SERVERS=https://etcd-0.etcd-headless.oci-service-broker.svc.cluster.local:2379,https://etcd-1.etcd-headless.oci-service-broker.svc.cluster.local:2379,https://etcd-2.etcd-headless.oci-service-broker.svc.cluster.local:2379
+ shift
+ shift
+ ((  2 > 0  ))
+ case "${1}" in
+ ETCD_CLIENT_TLS_ENABLED=true
+ shift
+ shift
+ ((  0 > 0  ))
+ export LD_LIBRARY_PATH=/openssl/lib
+ LD_LIBRARY_PATH=/openssl/lib
+ '[' false = true ']'
+ LIB_DIR=/oci-service-broker/lib
+ ls /oci-service-broker/lib/oci-java-sdk-full-1.22.1.jar
+ [[ true == \t\r\u\e ]]
+ [[ -f /oci-service-broker/etcdTlsSecret/etcd-client-ca.crt ]]
+ ETCD_CA_PATH=/oci-service-broker/etcdTlsSecret/etcd-client-ca.crt
+ [[ -f /oci-service-broker/etcdTlsSecret/etcd-client.crt ]]
+ ETCD_CRT_PATH=/oci-service-broker/etcdTlsSecret/etcd-client.crt
+ [[ -f /oci-service-broker/etcdTlsSecret/etcd-client.key ]]
+ ETCD_KEY_PATH=/oci-service-broker/etcdTlsSecret/etcd-client.key
+ exec java -cp '/oci-service-broker/lib/*' -Dport=9998 -Dtenancy=ocid1.tenancy.oc1..xxx -Dfingerprint=xxx -Duser=ocid1.user.oc1..xxx -Dpassphrase= -Dprivatekey=/var/run/oci-service-broker/privatekey -DregionId=us-ashburn-1 -Djava.util.logging.config.file=/oci-service-broker/config/jul-config.properties -DlogLevel=INFO -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO -Dio.netty.noUnsafe=true -DapiServerCaCert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt -DtlsEnabled=false -DstoreType=etcd -Detcd.servers=https://etcd-0.etcd-headless.oci-service-broker.svc.cluster.local:2379,https://etcd-1.etcd-headless.oci-service-broker.svc.cluster.local:2379,https://etcd-2.etcd-headless.oci-service-broker.svc.cluster.local:2379 -DetcdTlsEnabled=true -DCAPath=/oci-service-broker/etcdTlsSecret/etcd-client-ca.crt -DetcdClientCert=/oci-service-broker/etcdTlsSecret/etcd-client.crt -DetcdClientKey=/oci-service-broker/etcdTlsSecret/etcd-client.key -Dk8sApiTokenFile=/var/run/secrets/kubernetes.io/serviceaccount/token -Djdk.tls.client.protocols=TLSv1.2 com.oracle.oci.osb.Broker
2020-12-18 00:23:48.815|INFO|com.oracle.oci.osb.Broker|Initializing Logger.. 
2020-12-18 00:23:48.834|INFO|com.oracle.oci.osb.Broker|Starting OCI Service Broker... 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2020-12-18 00:23:52.907|WARNING|com.oracle.oci.osb.Broker|Insecure configuration found. TLS is not enabled. It is highly recommended to enable TLS. 
2020-12-18 00:23:53.584|INFO|com.oracle.oci.osb.Broker|Started OCI Service Broker: listening in port 9998 
2020-12-18 00:24:00.640|WARNING|org.glassfish.jersey.internal.Errors|The following warnings have been detected: WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 2
java.lang.ExceptionInInitializerError
	at com.oracle.oci.osb.api.OSBV2API.<init>(OSBV2API.java:156)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1375)
	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:272)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:366)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:710)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:184)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:54)
	at org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:129)
	at org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:284)
	at org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:75)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:110)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:93)
	at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:62)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.jdkhttp.JdkHttpHandlerContainer.handle(JdkHttpHandlerContainer.java:159)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at com.oracle.oci.osb.store.EtcdStore.<init>(EtcdStore.java:93)
	at com.oracle.oci.osb.store.DataStoreFactory.createDataStore(DataStoreFactory.java:38)
	at com.oracle.oci.osb.store.DataStoreFactory.<clinit>(DataStoreFactory.java:13)
	... 53 more
Caused by: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:195)
	at com.oracle.oci.osb.store.EtcdStore.<init>(EtcdStore.java:78)
	... 55 more
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:124)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:107)
	at io.netty.buffer.AbstractDerivedByteBuf.release0(AbstractDerivedByteBuf.java:89)
	at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:85)
	at io.netty.handler.ssl.SslContext.getCertificatesFromBuffers(SslContext.java:1102)
	at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1078)
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:193)
	... 56 more
MultiException stack 2 of 2
java.lang.IllegalStateException: Unable to perform operation: create on com.oracle.oci.osb.api.OSBV2API
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:393)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:710)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:184)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:54)
	at org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:129)
	at org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:284)
	at org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:75)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:110)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:93)
	at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:62)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.jdkhttp.JdkHttpHandlerContainer.handle(JdkHttpHandlerContainer.java:159)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by streamnsight** [comment]
Apparently a self-signed cert doesn't do, it needs to be signed by a CA even if it is my own CA.
